name: Draft PR Created

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  handle-draft-pr:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Handle Draft PR
      run: python .github/scripts/handle_draft_pr.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
