name: PR Merged

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  handle-pr-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Handle Merged PR
      run: python .github/scripts/handle_pr_merged.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
