name: PR Ready for Review

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - main

jobs:
  handle-pr-ready:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Handle PR Ready for Review
      run: python .github/scripts/handle_pr_ready.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
